export default class Constants {
  static readonly FULL_LENGTH = '100%';
  static readonly COMMON_LENGTH = '90%';
  static readonly MAIN_TARGET_HEIGHT = '24%';
  static readonly HOME_TAB_INDEX = 0;
  static readonly MINE_TAB_INDEX = 1;
  static readonly SPACING_EXTRA_SMALL = 4;
  static readonly SPACING_SMALL = 8;
  static readonly SPACING_MEDIUM = 16;
  static readonly SPACING_LARGE = 32;
  static readonly SPACING_EXTRA_LARGE = 60;
  static readonly LENGTH_SIXTY = 60;
  static readonly LENGTH_HUNDRED = 100;
  static readonly COLON = ':';
  static readonly SPACE = ' ';
}